name: Read PR Template Details

on:
  pull_request:
    # types: [opened, edited, synchronize]
    types:
      - closed
    branches: [ 'prod' ]

jobs:
  extract-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # - name: Set up GitHub CLI
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # - name: Fetch PR details
      #   id: pr-details
      #   run: |
      #     gh pr view ${{ github.event.pull_request.number }} --json body -q .body > pr_body.txt
      #     PR_BODY=$(cat pr_body.txt)
      #     echo "Fetched PR Body: $PR_BODY"
      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"
         
          # Extract image tags from the PR description
          PRD_AP=$(echo "$PR_BODY" | grep -A 3 "PRD Environment" | grep "AP Region:" | awk -F'`' '{print $2}')          
          PRD_EU=$(echo "$PR_BODY" | grep -A 3 "PRD Environment" | grep "EU Region:" | awk -F'`' '{print $2}')
          PRD_US=$(echo "$PR_BODY" | grep -A 3 "PRD Environment" | grep "US Region:" | awk -F'`' '{print $2}') 
          echo "PRD_AP=$PRD_AP" >> $GITHUB_ENV
          echo "PRD_EU=$PRD_EU" >> $GITHUB_ENV
          echo "PRD_US=$PRD_US" >> $GITHUB_ENV

          echo "Extracted Image Tags:"
          echo "AP Region: $PRD_AP"
          echo "EU Region: $PRD_EU"
          echo "US Region: $PRD_US"
          
      - name: Print image tags for debugging
        run: |
          echo "AP Region: $PRD_AP"
          echo "EU Region: $PRD_EU"
          echo "US Region: $PRD_US"
        
